version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./.docker/php.Dockerfile
    volumes:
      - ./:/app
  mysql:
    image: mariadb:latest
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: osticket
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticket
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  mailcatcher:
    image: schickling/mailcatcher
    platform: linux/amd64
    ports:
      - "1080:1080"
volumes:
  mysql: {}
